// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoipLk7ELXzS43Ngln_S374UepHF21xfs',
    appId: '1:280606418822:web:7e9711fe11ba50fe9dee07',
    messagingSenderId: '280606418822',
    projectId: 'dofix-tech',
    authDomain: 'dofix-tech.firebaseapp.com',
    storageBucket: 'dofix-tech.firebasestorage.app',
    measurementId: 'G-69LVEHDEB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwn5nGDWNjd_YZuvDHka-__FQ1MhdYulQ',
    appId: '1:280606418822:android:800c7614ab611cf89dee07',
    messagingSenderId: '280606418822',
    projectId: 'dofix-tech',
    storageBucket: 'dofix-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDii-KcK_of_6XEqCOwwKvHOFYomxu-Ol8',
    appId: '1:280606418822:ios:c137406bca9616ec9dee07',
    messagingSenderId: '280606418822',
    projectId: 'dofix-tech',
    storageBucket: 'dofix-tech.firebasestorage.app',
    iosBundleId: 'com.dofix.appcustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDii-KcK_of_6XEqCOwwKvHOFYomxu-Ol8',
    appId: '1:280606418822:ios:b2aa45d0dbd3296e9dee07',
    messagingSenderId: '280606418822',
    projectId: 'dofix-tech',
    storageBucket: 'dofix-tech.firebasestorage.app',
    iosBundleId: 'com.example.fixOnMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoipLk7ELXzS43Ngln_S374UepHF21xfs',
    appId: '1:280606418822:web:7e9711fe11ba50fe9dee07',
    messagingSenderId: '280606418822',
    projectId: 'dofix-tech',
    authDomain: 'dofix-tech.firebaseapp.com',
    storageBucket: 'dofix-tech.firebasestorage.app',
    measurementId: 'G-69LVEHDEB2',
  );
}
